# Generated by Django 4.2.19 on 2025-03-22 15:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_band', models.CharField(max_length=25, unique=True)),
                ('genre', models.CharField(choices=[('genre', 'GENRE'), ('pop', 'POP'), ('rock', 'ROCK'), ('blues', 'BLUES'), ('jazz', 'JAZZ'), ('other', 'OTHER')], default='genre', max_length=6)),
                ('number_of_members', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
