# Generated by Django 4.2.19 on 2025-03-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0003_post_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='marks_out_of_five',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='your_thoughs_on_this_band',
        ),
    ]
