# Generated by Django 4.2.19 on 2025-03-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0004_rename_rating_post_marks_out_of_five_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='your_thoughs_on_this_band',
            new_name='your_thoughts_on_this_band',
        ),
    ]
