# Generated by Django 4.2.19 on 2025-03-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0005_rename_your_thoughs_on_this_band_post_your_thoughts_on_this_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='your_thoughts_on_this_band',
            new_name='band_review',
        ),
    ]
