# Generated by Django 4.2.19 on 2025-03-23 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0006_rename_your_thoughts_on_this_band_post_band_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('genre', 'GENRE'), ('pop', 'POP'), ('rock', 'ROCK'), ('blues', 'BLUES'), ('jazz', 'JAZZ'), ('other', 'OTHER')], default='genre', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_members',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
