# Generated by Django 4.2.19 on 2025-03-25 18:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_bands', '0010_rename_post_band'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Band',
            new_name='Post',
        ),
    ]
