# Generated by Django 4.2.19 on 2025-03-25 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_bands', '0011_rename_band_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Band_Post',
        ),
    ]
