# Generated by Django 4.2.19 on 2025-03-29 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0012_rename_post_band_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='band',
            new_name='name_of_band',
        ),
        migrations.AlterField(
            model_name='band_post',
            name='band_review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='band_post',
            name='genre',
            field=models.CharField(choices=[('genre', 'GENRE'), ('pop', 'POP'), ('rock', 'ROCK'), ('blues', 'BLUES'), ('jazz', 'JAZZ'), ('other', 'OTHER')], default='genre', max_length=6),
        ),
        migrations.AlterField(
            model_name='band_post',
            name='marks_out_of_five',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='band_post',
            name='name_of_band',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='band_post',
            name='number_of_members',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='your_thoughts',
            field=models.TextField(),
        ),
    ]
