# Generated by Django 4.2.19 on 2025-03-30 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_bands', '0013_rename_band_opinion_name_of_band_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Band_Post',
            new_name='BandPost',
        ),
    ]
