# Generated by Django 4.2.19 on 2025-04-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0014_rename_band_post_bandpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandpost',
            name='size_of_venue_played',
            field=models.CharField(choices=[('venue', 'VENUE'), ('pub_small_venue', 'PUB/SMALL VENUE'), ('club', 'CLUB'), ('arena', 'ARENA'), ('stadium', 'STADIUM')], default='venue', max_length=20),
        ),
    ]
