# Generated by Django 4.2.19 on 2025-04-17 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0015_bandpost_size_of_venue_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpost',
            name='genre',
            field=models.CharField(choices=[('Genre', 'GENRE'), ('Pop', 'POP'), ('Rock', 'ROCK'), ('Blues', 'BLUES'), ('Jazz', 'JAZZ'), ('Other', 'OTHER')], default='genre', max_length=6),
        ),
        migrations.AlterField(
            model_name='bandpost',
            name='number_of_members',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='bandpost',
            name='size_of_venue_played',
            field=models.CharField(choices=[('Venue', 'VENUE'), ('Pub/Small Venue', 'PUB/SMALL VENUE'), ('Club', 'CLUB'), ('Arena', 'ARENA'), ('Stadium', 'STADIUM')], default='venue', max_length=20),
        ),
    ]
