# Generated by Django 4.2.19 on 2025-04-17 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0016_alter_bandpost_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpost',
            name='genre',
            field=models.CharField(choices=[('Please select', 'PLEASE SELECT'), ('Pop', 'POP'), ('Rock', 'ROCK'), ('Blues', 'BLUES'), ('Jazz', 'JAZZ'), ('Other', 'OTHER')], default='Please select'),
        ),
        migrations.AlterField(
            model_name='bandpost',
            name='number_of_members',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='bandpost',
            name='size_of_venue_played',
            field=models.CharField(choices=[('Please select', 'PLEASE SELECT'), ('Pub/Small Venue', 'PUB/SMALL VENUE'), ('Club', 'CLUB'), ('Arena', 'ARENA'), ('Stadium', 'STADIUM')], default='Please select'),
        ),
    ]
