# Generated by Django 4.2.19 on 2025-04-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0017_alter_bandpost_genre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
