# Generated by Django 4.2.19 on 2025-04-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0018_delete_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpost',
            name='size_of_venue_played',
            field=models.CharField(choices=[('Please select', 'PLEASE SELECT'), ('Pub', 'PUB'), ('Club', 'CLUB'), ('Arena', 'ARENA'), ('Stadium', 'STADIUM')], default='Please select'),
        ),
    ]
