# Generated by Django 4.2.19 on 2025-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0019_alter_bandpost_size_of_venue_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpost',
            name='marks_out_of_five',
            field=models.IntegerField(choices=[('Please select', 'PLEASE SELECT'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Please select'),
        ),
        migrations.AlterField(
            model_name='bandpost',
            name='number_of_members',
            field=models.IntegerField(choices=[('Please select', 'PLEASE SELECT'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6 or more', '6 OR MORE')], default='Please select'),
        ),
    ]
