# Generated by Django 4.2.19 on 2025-04-19 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_bands', '0020_alter_bandpost_marks_out_of_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpost',
            name='marks_out_of_five',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='bandpost',
            name='number_of_members',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
